print("/////////////////////////////////////")
print("//    Extane Core - Loading....    //")
print("/////////////////////////////////////")
print("//    Extane Core - Shared Code    //")
print("/////////////////////////////////////")
include("autorun/shared/shared.lua")

if SERVER then
    print("/////////////////////////////////////")
    print("//    Extane Core - Server Code    //")
    print("/////////////////////////////////////")
    print("//      Server Code - Events       //")
    print("/////////////////////////////////////")
    print("//    Extane Core - None Loaded    //")
    print("/////////////////////////////////////")
    print("//   Server Code - Chat Messages   //")
    print("/////////////////////////////////////")
    print("//     Chat Messages - General     //")
    print("/////////////////////////////////////")
    include("autorun/server/chat/general/give.lua")
    print("/////////////////////////////////////")
    print("//   Chat Messages - Moderation    //")
    print("/////////////////////////////////////")
    include("autorun/server/chat/moderation/kick.lua")
    print("/////////////////////////////////////")
    print("// Server Code - Console Commands  //")
    print("/////////////////////////////////////")
    print("//    Extane Core - None Loaded    //")
    AddCSLuaFile("autorun/shared/shared.lua")
else
    print("/////////////////////////////////////")
    print("//    Extane Core - Client Code    //")
    print("/////////////////////////////////////")
    print("//    Extane Core - None Loaded    //")
end

print("/////////////////////////////////////")
print("//    Extane Core - All Loaded.    //")
print("/////////////////////////////////////")
